#!/bin/sh
# Configure an installed Debian/Ubuntu root so it can boot from iSCSI.
# Intended to run inside a chroot (after live-ISO install onto an iSCSI LUN).
#
# Usage (from live environment):
#   chroot /mnt /tmp/iscsi-boot-fixup-debian.sh \
#     --portal 192.168.88.15:3260 \
#     --iqn iqn.2026-09.local.iscsi-s3:disk0 \
#     [--username USER --password SECRET] \
#     [--initiator-iqn iqn.1993-08.org.debian:01:installer]
#
# See docs/users/iscsi-os-install.md

set -eu

PORTAL=""
IQN=""
USERNAME=""
PASSWORD=""
INITIATOR_IQN=""

usage() {
  sed -n '2,14p' "$0" | tr -d '#'
  exit "${1:-0}"
}

while [ $# -gt 0 ]; do
  case "$1" in
    --portal) PORTAL="${2:-}"; shift 2 ;;
    --iqn) IQN="${2:-}"; shift 2 ;;
    --username) USERNAME="${2:-}"; shift 2 ;;
    --password) PASSWORD="${2:-}"; shift 2 ;;
    --initiator-iqn) INITIATOR_IQN="${2:-}"; shift 2 ;;
    -h|--help) usage 0 ;;
    *) echo "unknown argument: $1" >&2; usage 1 ;;
  esac
done

if [ -z "$PORTAL" ] || [ -z "$IQN" ]; then
  echo "error: --portal and --iqn are required" >&2
  usage 1
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "error: must run as root (inside chroot)" >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

echo "==> Installing open-iscsi and initramfs tools"
apt-get update -y
apt-get install -y open-iscsi initramfs-tools

# Bootloader helpers (best-effort; install may already have them)
if [ -d /sys/firmware/efi ]; then
  apt-get install -y grub-efi-amd64 || apt-get install -y grub-efi-arm64 || true
else
  apt-get install -y grub-pc || true
fi

if [ -n "$INITIATOR_IQN" ]; then
  echo "==> Setting initiator IQN"
  mkdir -p /etc/iscsi
  echo "InitiatorName=$INITIATOR_IQN" > /etc/iscsi/initiatorname.iscsi
fi

echo "==> Ensuring iscsid defaults"
mkdir -p /etc/iscsi
if [ -f /etc/iscsi/iscsid.conf ]; then
  # Prefer manual startup control via node records + initramfs
  sed -i 's/^node.startup.*/node.startup = manual/' /etc/iscsi/iscsid.conf 2>/dev/null || true
fi

echo "==> Writing open-iscsi node for $IQN @ $PORTAL"
# discovery may fail offline; create/update node record directly when possible
if iscsiadm -m discovery -t sendtargets -p "$PORTAL" >/tmp/iscsi-discovery.out 2>/dev/null; then
  cat /tmp/iscsi-discovery.out || true
else
  echo "warning: discovery failed (offline chroot is OK); configuring node record anyway" >&2
  iscsiadm -m node -T "$IQN" -p "$PORTAL" -o new 2>/dev/null || true
fi

iscsiadm -m node -T "$IQN" -p "$PORTAL" -o update -n node.startup -v automatic || \
  iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.startup -v automatic

if [ -n "$USERNAME" ]; then
  iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.session.auth.authmethod -v CHAP
  iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.session.auth.username -v "$USERNAME"
  iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.session.auth.password -v "$PASSWORD"
fi

# Useful when the session should survive replace-and-reboot style recovery
iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.conn[0].startup -v automatic 2>/dev/null || true

echo "==> Enabling ISCSI_AUTO for initramfs"
mkdir -p /etc/iscsi
cat > /etc/iscsi/iscsi.initramfs <<EOF
# Generated by iscsi-boot-fixup-debian.sh
ISCSI_AUTO=true
EOF

echo "==> Adding iSCSI modules to initramfs"
MODULES_FILE=/etc/initramfs-tools/modules
touch "$MODULES_FILE"
for mod in iscsi_tcp iscsi_ibft libiscsi libiscsi_tcp scsi_transport_iscsi; do
  grep -qxF "$mod" "$MODULES_FILE" 2>/dev/null || echo "$mod" >> "$MODULES_FILE"
done

HOOK=/etc/initramfs-tools/hooks/iscsi-extra-modules
if [ ! -f "$HOOK" ]; then
  cat > "$HOOK" <<'EOF'
#!/bin/sh
# Ensure core iSCSI modules land in the initramfs image.
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in
  prereqs) prereqs; exit 0 ;;
esac
. /usr/share/initramfs-tools/hook-functions
for mod in iscsi_tcp iscsi_ibft libiscsi libiscsi_tcp scsi_transport_iscsi; do
  manual_add_modules "$mod" 2>/dev/null || true
done
EOF
  chmod +x "$HOOK"
fi

echo "==> Updating GRUB cmdline hints (idempotent)"
GRUB_FILE=/etc/default/grub
if [ -f "$GRUB_FILE" ]; then
  # RD.ISCSI.IBFT helps dracut-style stacks; harmless if unused.
  # ip=dhcp helps bring a NIC up before iscsistart when not using iBFT.
  NEED="RD.ISCSI.IBFT=1"
  if ! grep -q 'GRUB_CMDLINE_LINUX=.*RD.ISCSI.IBFT' "$GRUB_FILE" 2>/dev/null; then
    if grep -q '^GRUB_CMDLINE_LINUX=' "$GRUB_FILE"; then
      sed -i 's/^GRUB_CMDLINE_LINUX="\(.*\)"/GRUB_CMDLINE_LINUX="\1 '"$NEED"' ip=dhcp"/' "$GRUB_FILE"
    else
      echo "GRUB_CMDLINE_LINUX=\"$NEED ip=dhcp\"" >> "$GRUB_FILE"
    fi
  fi
fi

echo "==> Rebuilding initramfs"
update-initramfs -u -k all

echo "==> Updating GRUB"
if command -v update-grub >/dev/null 2>&1; then
  update-grub
elif command -v grub-mkconfig >/dev/null 2>&1; then
  grub-mkconfig -o /boot/grub/grub.cfg
fi

# Enable services for later soft reboots (not only cold iBFT boot)
systemctl enable iscsid.service 2>/dev/null || true
systemctl enable open-iscsi.service 2>/dev/null || true

echo "==> Done."
echo "    Portal=$PORTAL IQN=$IQN"
echo "    Reminder: ESP should be mounted at /boot/efi when regenerating GRUB on UEFI."
echo "    Exit chroot, umount -R /mnt, iscsi logout, then reboot."
