#!/bin/sh
# Configure an installed Alpine root so it can boot from iSCSI.
# Intended to run inside a chroot (after live-ISO / setup-disk onto an iSCSI LUN).
#
# Usage (from live environment):
#   chroot /mnt /tmp/iscsi-boot-fixup-alpine.sh \
#     --portal 192.168.88.15:3260 \
#     --iqn iqn.2026-09.local.iscsi-s3:disk0 \
#     [--username USER --password SECRET] \
#     [--initiator-iqn iqn.1993-08.org.alpinelinux:boot]
#
# See docs/users/iscsi-os-install.md

set -eu

PORTAL=""
IQN=""
USERNAME=""
PASSWORD=""
INITIATOR_IQN=""

usage() {
  sed -n '2,14p' "$0" | tr -d '#'
  exit "${1:-0}"
}

while [ $# -gt 0 ]; do
  case "$1" in
    --portal) PORTAL="${2:-}"; shift 2 ;;
    --iqn) IQN="${2:-}"; shift 2 ;;
    --username) USERNAME="${2:-}"; shift 2 ;;
    --password) PASSWORD="${2:-}"; shift 2 ;;
    --initiator-iqn) INITIATOR_IQN="${2:-}"; shift 2 ;;
    -h|--help) usage 0 ;;
    *) echo "unknown argument: $1" >&2; usage 1 ;;
  esac
done

if [ -z "$PORTAL" ] || [ -z "$IQN" ]; then
  echo "error: --portal and --iqn are required" >&2
  usage 1
fi

if [ "$(id -u)" -ne 0 ]; then
  echo "error: must run as root (inside chroot)" >&2
  exit 1
fi

echo "==> Installing open-iscsi and boot tooling"
apk update
apk add open-iscsi busybox-openrc
if [ -d /sys/firmware/efi ]; then
  apk add grub grub-efi efibootmgr || true
else
  apk add grub grub-bios || true
fi

if [ -n "$INITIATOR_IQN" ]; then
  echo "==> Setting initiator IQN"
  mkdir -p /etc/iscsi
  echo "InitiatorName=$INITIATOR_IQN" > /etc/iscsi/initiatorname.iscsi
fi

echo "==> Writing open-iscsi node for $IQN @ $PORTAL"
mkdir -p /etc/iscsi
if iscsiadm -m discovery -t sendtargets -p "$PORTAL" >/tmp/iscsi-discovery.out 2>/dev/null; then
  cat /tmp/iscsi-discovery.out || true
else
  echo "warning: discovery failed (offline chroot is OK); configuring node record anyway" >&2
  iscsiadm -m node -T "$IQN" -p "$PORTAL" -o new 2>/dev/null || true
fi

iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.startup -v automatic || true

if [ -n "$USERNAME" ]; then
  iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.session.auth.authmethod -v CHAP
  iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.session.auth.username -v "$USERNAME"
  iscsiadm -m node -T "$IQN" -p "$PORTAL" --op update -n node.session.auth.password -v "$PASSWORD"
fi

echo "==> Enabling iscsid at boot"
if command -v rc-update >/dev/null 2>&1; then
  rc-update add iscsid default 2>/dev/null || true
  # Some Alpine images ship open-iscsi helpers under this name:
  rc-update add iscsi default 2>/dev/null || true
fi

echo "==> Ensuring mkinitfs includes iSCSI support"
# Alpine mkinitfs features live in /etc/mkinitfs/mkinitfs.conf
MKCONF=/etc/mkinitfs/mkinitfs.conf
if [ -f "$MKCONF" ]; then
  # shellcheck disable=SC2016
  if grep -q '^features=' "$MKCONF"; then
    if ! grep -q 'iscsi' "$MKCONF"; then
      sed -i 's/^features="\(.*\)"/features="\1 iscsi"/' "$MKCONF"
    fi
  else
    echo 'features="base ata scsi usb virtio network iscsi"' >> "$MKCONF"
  fi
else
  mkdir -p /etc/mkinitfs
  cat > "$MKCONF" <<'EOF'
features="base ata scsi usb virtio network iscsi"
EOF
fi

# Drop a modules list some setups honor alongside features=
MODFILE=/etc/mkinitfs/features.d/iscsi.modules
if [ ! -f "$MODFILE" ]; then
  mkdir -p /etc/mkinitfs/features.d
  cat > "$MODFILE" <<'EOF'
kernel/drivers/scsi/scsi_transport_iscsi*
kernel/drivers/scsi/libiscsi*
kernel/drivers/scsi/iscsi_tcp*
kernel/drivers/firmware/iscsi_ibft*
EOF
fi

echo "==> Updating extlinux/grub cmdline hints when present"
# GRUB
if [ -f /etc/default/grub ]; then
  if ! grep -q 'GRUB_CMDLINE_LINUX_DEFAULT=.*iscsi' /etc/default/grub 2>/dev/null; then
    if grep -q '^GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub; then
      sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="\(.*\)"/GRUB_CMDLINE_LINUX_DEFAULT="\1 ip=dhcp"/' /etc/default/grub
    else
      echo 'GRUB_CMDLINE_LINUX_DEFAULT="ip=dhcp"' >> /etc/default/grub
    fi
  fi
fi

# Persist portal/iqn for operators (documentation in-root)
mkdir -p /etc/iscsi
cat > /etc/iscsi/iscsi-boot.env <<EOF
# Generated by iscsi-boot-fixup-alpine.sh
ISCSI_PORTAL=$PORTAL
ISCSI_TARGET_IQN=$IQN
EOF

echo "==> Rebuilding initramfs (mkinitfs)"
KVER="$(uname -r)"
if [ -d "/lib/modules/$KVER" ]; then
  mkinitfs "$KVER"
else
  # Inside chroot, running kernel may differ from installed modules — rebuild all
  for d in /lib/modules/*; do
    [ -d "$d" ] || continue
    ver=$(basename "$d")
    echo "    mkinitfs $ver"
    mkinitfs "$ver" || true
  done
fi

echo "==> Refreshing GRUB config"
if command -v grub-mkconfig >/dev/null 2>&1; then
  mkdir -p /boot/grub
  grub-mkconfig -o /boot/grub/grub.cfg || true
fi

echo "==> Done."
echo "    Portal=$PORTAL IQN=$IQN"
echo "    Exit chroot, umount -R /mnt, iscsi logout, then reboot."
echo "    For UEFI, confirm ESP is mounted at /boot/efi before relying on grub-mkconfig."
